### ISSUE TITLE
Не ловятся исключения оптимайзеров

### ISSUE THREAD

**Issue by SnetkovR** [AndrewUsoltsev/TOOP_Optimize#13]

**Comment by AndrewUsoltsev** [comment]
кинь пример входных данных

**Comment by SnetkovR** [comment]
В данном случае входные данные не очень важны. Вбиваешь любые корректные данные, например для LSM и оптимайзером GradientDescent, в этом случае будет выбрасываться исключение, о том что у функционала не задан дифференциал, однако оно не ловиться

**Comment by SnetkovR** [comment]
> кинь пример входных данных

В данном случае входные данные не очень важны. Вбиваешь любые корректные данные, например для LSM и оптимайзером GradientDescent, в этом случае будет выбрасываться исключение, о том что у функционала не задан дифференциал, однако оно не ловиться

**Comment by SnetkovR** [comment]
Сначала так 
![image](https://user-images.githubusercontent.com/36268133/55957429-8b158480-5c90-11e9-9603-cc9c83314e27.png)
Потом так 
![image](https://user-images.githubusercontent.com/36268133/55957442-95378300-5c90-11e9-99a5-37f9e86164e2.png)

**Comment by AndrewUsoltsev** [comment]
Вроде все ловится
![image](https://user-images.githubusercontent.com/25631708/55963518-2f052d00-5c9d-11e9-8132-847c918ab8e6.png)

**Comment by AndrewUsoltsev** [comment]
Подправил
