### ISSUE TITLE
Баг с редактированием формы "Настройки оптимайзера"

### ISSUE THREAD

**Issue by SnetkovR** [AndrewUsoltsev/TOOP_Optimize#14]
![image](https://user-images.githubusercontent.com/36268133/55929309-34835880-5c46-11e9-93c6-1fc5fa4f89f3.png)
Если я редактирую значение погрешности в этой форме мне в конструктор оптимайзера приходит нулевой момент времени
![image](https://user-images.githubusercontent.com/36268133/55929373-86c47980-5c46-11e9-8dc0-54d2ad87cd22.png)

**Comment by AndrewUsoltsev** [comment]
Исправил
