### ISSUE TITLE
Не нужно выкидывать стек трейс, пожалуйста

### ISSUE THREAD

**Issue by SnetkovR** [AndrewUsoltsev/TOOP_Optimize#15]

**Comment by AndrewUsoltsev** [comment]
![8393_D000M0000_596535424EDR_F0000_0106M1-stretch_web](https://user-images.githubusercontent.com/25631708/55961594-71c50600-5c99-11e9-9c5e-3d31c102b71b.jpg)

**Comment by AndrewUsoltsev** [comment]
![d8bac2f9ff3ecacf3233bb7e2cefbd47](https://user-images.githubusercontent.com/25631708/55961626-81dce580-5c99-11e9-839a-4c3331e71047.jpg)

**Comment by SnetkovR** [comment]
Сук, ну ладно

**Comment by AndrewUsoltsev** [comment]
Зря закрыл
